import Navbar from "./_components/navbar/Navbar";
import "./globals.css";
import { Merriweather_Sans } from "next/font/google";
import AuthContext from "./_context/AuthContext";
import getCurrentUser from "./_actions/getCurrentUser";
import { Tooltip } from "react-tooltip";
import Section from "./_components/Section";
import clsx from "clsx";

const merriweatherSans = Merriweather_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  console.log(currentUser);
  return (
    <html lang="en">
      <body
        className={clsx(
          merriweatherSans.className,
          "bg-white",
          "text-gray-600 h-[100vh] relative max-w-5xl mx-auto flex flex-col"
        )}
      >
        <AuthContext>
          <Navbar />
          <Section>{children}</Section>
        </AuthContext>
      </body>
    </html>
  );
}
// linear-gradient(to right, #0f2027, #203a43, #2c5364);
