import Navbar from "./_components/navbar/Navbar";
import "./globals.css";
import { Merriweather_Sans } from "next/font/google";
import AuthContext from "./_context/AuthContext";
import getCurrentUser from "./_actions/getCurrentUser";
import { Tooltip } from "react-tooltip";

const merriweatherSans = Merriweather_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  console.log(currentUser);
  return (
    <html lang="en">
      <body
        className={`${merriweatherSans.className} bg-stone-50 text-gray-600 h-full`}
      >
        <AuthContext>
          <main className={`max-w-4xl mx-auto`}>
            <Navbar />
            <div className="h-[100vh]">{children}</div>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
